live: False
max_events: 10000
batch_size: 1000
xpand: True
h5:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/test/h5/
  name1: run
  name2: .h5
log:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/test/log/

 
data:
  uniform:
    hit_l:
      fvar: [n]
    
  # ragged_split:
  #   tpks_l:
  #     var: [mcp,u1,u2,v1,v2,w1,w2]
  #   hpks_l:
  #     var: [mcp,u1,u2,v1,v2,w1,w2]      
    # diag_l:
    #   var: [tsum_u, tsum_v, tsum_w, diff_u, diff_v, diff_w]

  ragged:
    # hit_s:
    #   var: [z, y, t, m]
    hit_l:
      var: [z, y, t, m]     
    # diag_l:
    #   var: [tsum_u, tsum_v, tsum_w, diff_u, diff_v, diff_w]


  x:
    scan: [var1, var2]
    bld: [gmd, xgmd]
    timing: ['280','281','282','dest']
    atm: [edge, prom] 
    epics: [las_ip2_atm_dly]

