live: False
max_events: 1000000
batch_size: 1000
h5:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/xiangli/h5/
  name1: run
  name2: .h5
log:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/xiangli/log/

# h5:
#   path1: /sdf/data/lcls/ds/tmo/
#   path2: /scratch/xiangli/h5/
#   name1: run
#   name2: .h5
# log:
#   path1: /sdf/data/lcls/ds/tmo/
#   path2: /scratch/xiangli/log/
  
data:
  # uniform:
  #   tpks_l:
  #     len: 10
  #     var: [mcp, u1]
  #   hit_l:
  #     len: 10
  #     fvar: [n]
  #     var: [x, y, t, m]
  ragged:
  #    tpks_l:
  #    var: [mcp, u1]  
    hit_s:
      var: [z, y, t]
    hit_l:
      var: [z, y, t]  
    ppc_l:
      var: [pp1, pp2]
    tpc_l:
      var: [tp1, tp2, tp3]
      

  x:
    scan: [var1, var2]
    bld: [gmd, xgmd]
    timing: ['280','281','282','dest']
    

